#!/bin/bash

 FileisArchive()
        {
                Vtest=`head -n 1 $1 | egrep '[0-9]+:[0-9]+' `
                if [[ -n $Vtest ]]; then
                        echo "1"
                else
                        echo "0" 
                fi
        }
list() {
echo "fonction list"
 for fichier in `ls`
                do
                        if [[ `FileisArchive $fichier` == "1" ]]; then
                                echo $fichier 
                        fi
                done
}

BasePath() #cette fonction renvoie le chemin de base de l'archive 
        {
                bp=`grep -m1 "^directory " $archive | cut -d' ' -f2`
                echo $bp
        }

 getmsg() {
    while read line; do
        set -- $line 
        echo "$1"      
        echo "$2"
        echo "$3"
        echo "$4"
 case $1 in
        "ls")
                GetHeader $3 $2 #pas d'idée encore
                ;;
        "cd")
                path=`echo $2 | cut -d'/' -f1`
                TestPath=`grep -e "^directory Exemple/Test$3$path $" $4`

                        if [[ $2 == ".." ]]; then
                              echo $3 | sed -e 's/[^\/]*\/$//'
                        elif [[ $2 == "/" ]]; then
                                echo "/"
                        elif [[ -n $TestPath ]]; then
                                echo $3$2
                        else
                                echo -e "ce dossier n'existe pas"
                        fi
                ;;
        "cat")
                #recuperer les lignes ici et pas dans getfilecontent
                fichier=`cat $3 | grep -e "$2"`
                echo $fichier
                GetFileContent $3 $fichier
                ;;
        "rm")
                ;;

        "list")
                list
                ;;
esac

done
}

function CheckPort() {
#verifie si le port est correct
port=$1

        if [[ $port =~ ^[0-9]+$ ]] && [[ $port -ge 1 && $port -le 47823 ]]; then
        #verifie si le port est bien un nombre inférieur à 47823
                        echo "1"
                else
                        echo "0"
        fi
}

vsh_ls() {
grep -e "^directory Exemple/Test$3$path $" $4
 }

function GetHeader() {
    ligneHeader=$(cat $1  | grep -o "^[0-9]")
    ligneBody=$(cat $1  | grep -o "[0-9]*$")
    ligneBody=$(($ligneBody-1))

    #cat $1 | head -n ${ligneBody} | tail -n ${ligneHeader}
    cat $1 | sed -n  "${ligneHeader},${ligneBody}p"
}

function GetLNHeader() {
    ligne=$(GetLigneNumber $1)
    ligneHeader=$(echo $ligne | cut -d ':' -f1)
    echo $ligneHeader
}

function GetBody() {
    ligne=$(cat $1 | grep '^[0-9]*:[0-9]*')
    ligneHeader=$(echo $ligne | cut -d ':' -f1)
    ligneBody=$(echo $ligne | cut -d ':' -f2)

    awk -v n=$ligneBody 'NR>=n' $1
}
function GetLigneNumber() {
 ligne=$(cat $1 | grep '^[0-9]*:[0-9]*')
    #exemple : 3:25

    echo $ligne
}

GetLNBody() {

    ligne=$(GetLigneNumber $1)
    ligneBody=$(echo $ligne | cut -d ':' -f2)
    #exemple : 25

    echo $ligneBody
}

 GetFileSize() {
        #prend une ligne en argument 1
        #exemple : toto2 -rw-r--r-- 249 4 10

        echo $1 | grep -o -E '[0-9]+ [0-9]+ [0-9]+' | cut -d' ' -f1
}
 GetFileContent() {
#prend une archive en argument 1
#prend une ligne en argument 2
#exemple : toto2 -rw-r--r-- 249 4 10
echo "ahahaha"
fichier=$2
echo $fichier

    fileligne=$(echo $fichier | grep -o '[0-9]* [0-9]*$')
    #exemple 4:10
        echo "$fileligne"
    ligneBody=$(GetLNBody $1)


    start=$(echo $fileligne | cut -d ' ' -f1)
        echo "$start"
    end=$(echo $fileligne | cut -d ' ' -f2)
        echo "$end"
    #exemple : start=4 et end=10

    start=$(($start+$ligneBody))
    end=$(($end+$start))


  #  if [[ $(GetFileSize "$fichier") -ne 0 ]]; then
        cat $1 | sed -n  "${start},${end}p"
        #GetBody $1 | sed -n  "${start},${end}p"
   # fi
}
    
