#!/bin/bash




function IsPathAbsolute {
path="$2"
	if [[ ${path:0:1} = "/" ]]; then 
	#verifie si le caractere en position 0 et 1 dans l'arguement path est un "/"
		echo "1"
	else
		echo "0"
	fi
}

function CheckPort {
#verifie si le port est correct
port=$3

	if [[ $port =~ ^[0-9]+$ ]] && [[ $port -ge 1 && $port -le 47823 ]]; then 
	#verifie si le port est bien un nombre inférieur à 47823
			echo "1"
		else
			echo "0"
	fi
}

function GetPath {

if (IsPathAbsolute "$2"); then
		path=$2
	else
		pwd


}
