#!/bin/bash




function IsPathAbsolute {
path="$2"
	if [[ ${path:0:1} = "/" ]]; then 
	#verifie si le caractere en position 0 et 1 dans l'arguement path est un "/"
		echo "1"
	else
		echo "0"
	fi
}

function CheckPort {
#verifie si le port est correct
port=$3

	if [[ $port =~ ^[0-9]+$ ]] && [[ $port -ge 1 && $port -le 47823 ]]; then 
	#verifie si le port est bien un nombre inférieur à 47823
			echo "1"
		else
			echo "0"
	fi
}

function BasePath() #cette fonction renvoie le chemin de base de l'archive 
        {
                bp=`grep -m1 "^directory " $archive | cut -d' ' -f2`
                echo $bp
        }

function GetHeader() {
    ligne=$(cat $1 | grep '^[0-9]*:[0-9]*') 
    ligneHeader=$(echo $ligne | cut -d ':' -f1)
    ligneBody=$(echo $ligne | cut -d ':' -f2)


    #cat $1 | head -n ${ligneBody} | tail -n ${ligneHeader}
    cat $1 | sed -n  "${ligneHeader},${ligneBody}p"
}

function GetLNHeader() {
    ligne=$(GetLigneNumber $1)
    ligneHeader=$(echo $ligne | cut -d ':' -f1)
    echo $ligneHeader
}

function GetBody() {
    ligne=$(cat $1 | grep '^[0-9]*:[0-9]*') 
    ligneHeader=$(echo $ligne | cut -d ':' -f1)
    ligneBody=$(echo $ligne | cut -d ':' -f2)

    awk -v n=$ligneBody 'NR>=n' $1
}

function GetLigneNumber() {
    ligne=$(cat $1 | grep '^[0-9]*:[0-9]*')
    #exemple : 3:25

    echo $ligne
}

function GetLNBody() {
    ligne=$(GetLigneNumber $1)
    ligneBody=$(echo $ligne | cut -d ':' -f2)
    #exemple : 25

    echo $ligneBody
}

function GetFileSize() {
	#prend une ligne en argument 1
	#exemple : toto2 -rw-r--r-- 249 4 10

	echo $1 | grep -o -E '[0-9]+ [0-9]+ [0-9]+' | cut -d' ' -f1
}

function GetFileContent() {
#prend une archive en argument 1
#prend une ligne en argument 2
#exemple : toto2 -rw-r--r-- 249 4 10

fichier=$2


    fileligne=$(echo $fichier | grep -E -o '[0-9]* [0-9]*$')
    #exemple 4:10
    ligneBody=$(GetLNBody $1)

    
    start=$(echo $fileligne | cut -d ' ' -f1)
    end=$(echo $fileligne | cut -d ' ' -f2)
    #exemple : start=4 et end=10

    #awk -v a=$start -v b=$ligneBody '{a+=b} END {print a}'
    start=$(($start+$ligneBody))
    end=$(($end+$start))
    
    if [[ $(GetFileSize "$fichier") -ne 0 ]]; then
    	cat $1 | sed -n  "${start},${end}p"
    fi
    
    
}

